# Temporal dynamic configuration for development.
# Reference: https://docs.temporal.io/references/dynamic-configuration

system.forceSearchAttributesCacheRefreshOnRead:
  - value: true
    constraints: {}

# Lower poll intervals for faster feedback in development.
frontend.enableClientVersionCheck:
  - value: false
    constraints: {}

history.defaultActivityRetryPolicy:
  - value:
      InitialIntervalInSeconds: 1
      MaximumIntervalCoefficient: 100.0
      BackoffCoefficient: 2.0
      MaximumAttempts: 0
    constraints: {}
