import type { SeedSlo } from '../types.js';

export const acmeCorpSlos: SeedSlo[] = [
  {
    productSlug: 'customer-360',
    name: 'Profile freshness',
    description: 'New customer events appear in the unified profile within 6 hours of source ingest.',
    sloType: 'freshness',
    metricName: 'ingest_to_profile_lag_hours',
    thresholdOperator: 'lt',
    thresholdValue: 6,
    thresholdUnit: 'hours',
    evaluationWindowHours: 24,
  },
  {
    productSlug: 'customer-360',
    name: 'PII completeness',
    description: 'Hashed identifier fields are non-null on at least 95% of profile rows.',
    sloType: 'completeness',
    metricName: 'pii_field_non_null_rate',
    thresholdOperator: 'gte',
    thresholdValue: 0.95,
    thresholdUnit: 'ratio',
    evaluationWindowHours: 24,
  },
  {
    productSlug: 'campaign-attribution',
    name: 'Attribution freshness',
    description: 'Campaign attribution rolls up touchpoints from the last 24 hours within 12 hours of close.',
    sloType: 'freshness',
    metricName: 'attribution_window_lag_hours',
    thresholdOperator: 'lt',
    thresholdValue: 12,
    thresholdUnit: 'hours',
    evaluationWindowHours: 24,
  },
  {
    productSlug: 'campaign-attribution',
    name: 'Attribution API latency',
    description: 'p95 response time on the attribution REST endpoint stays below 500ms.',
    sloType: 'latency',
    metricName: 'attribution_p95_response_ms',
    thresholdOperator: 'lt',
    thresholdValue: 500,
    thresholdUnit: 'ms',
    evaluationWindowHours: 1,
  },
  {
    productSlug: 'inventory-daily',
    name: 'Daily snapshot freshness',
    description: 'Inventory snapshot is available by 08:00 UTC each trading day.',
    sloType: 'freshness',
    metricName: 'snapshot_availability_lag_hours',
    thresholdOperator: 'lte',
    thresholdValue: 8,
    thresholdUnit: 'hours',
    evaluationWindowHours: 24,
  },
  {
    productSlug: 'inventory-daily',
    name: 'SKU coverage',
    description: 'At least 99% of active SKUs from the source warehouse appear in the daily snapshot.',
    sloType: 'completeness',
    metricName: 'sku_coverage_rate',
    thresholdOperator: 'gte',
    thresholdValue: 0.99,
    thresholdUnit: 'ratio',
    evaluationWindowHours: 24,
  },
  {
    productSlug: 'supplier-performance',
    name: 'Weekly refresh',
    description: 'Supplier rollup refreshes every Monday by 09:00 UTC.',
    sloType: 'freshness',
    metricName: 'supplier_rollup_age_hours',
    thresholdOperator: 'lt',
    thresholdValue: 168,
    thresholdUnit: 'hours',
    evaluationWindowHours: 168,
  },
  {
    productSlug: 'supplier-performance',
    name: 'Reporting supplier coverage',
    description: 'At least 90% of active suppliers report at least one delivery in the rollup window.',
    sloType: 'completeness',
    metricName: 'reporting_supplier_rate',
    thresholdOperator: 'gte',
    thresholdValue: 0.9,
    thresholdUnit: 'ratio',
    evaluationWindowHours: 168,
  },
  {
    productSlug: 'revenue-daily',
    name: 'Daily reconciliation freshness',
    description: 'Daily revenue figures available within 6 hours of trading day close.',
    sloType: 'freshness',
    metricName: 'reconciliation_lag_hours',
    thresholdOperator: 'lt',
    thresholdValue: 6,
    thresholdUnit: 'hours',
    evaluationWindowHours: 24,
  },
  {
    productSlug: 'revenue-daily',
    name: 'Transaction reconciliation rate',
    description: 'At least 99.5% of inventory-movement transactions reconcile against revenue postings.',
    sloType: 'completeness',
    metricName: 'reconciliation_match_rate',
    thresholdOperator: 'gte',
    thresholdValue: 0.995,
    thresholdUnit: 'ratio',
    evaluationWindowHours: 24,
  },
  {
    productSlug: 'forecast-weekly',
    name: 'Weekly forecast publication',
    description: 'Forecast for the upcoming week publishes by Monday 09:00 UTC.',
    sloType: 'freshness',
    metricName: 'forecast_publication_age_hours',
    thresholdOperator: 'lt',
    thresholdValue: 168,
    thresholdUnit: 'hours',
    evaluationWindowHours: 168,
  },
  {
    productSlug: 'forecast-weekly',
    name: 'Forecast coverage',
    description: 'Forecast covers at least 95% of revenue-bearing product lines.',
    sloType: 'completeness',
    metricName: 'forecast_product_line_coverage',
    thresholdOperator: 'gte',
    thresholdValue: 0.95,
    thresholdUnit: 'ratio',
    evaluationWindowHours: 168,
  },
];
