import type { SeedSlo } from '../types.js';

export const betaIndustriesSlos: SeedSlo[] = [
  {
    productSlug: 'kyc-profiles',
    name: 'KYC verification freshness',
    description: 'New KYC verification records appear in the profile store within 1 hour of completion.',
    sloType: 'freshness',
    metricName: 'kyc_verification_lag_minutes',
    thresholdOperator: 'lt',
    thresholdValue: 60,
    thresholdUnit: 'minutes',
    evaluationWindowHours: 6,
  },
  {
    productSlug: 'kyc-profiles',
    name: 'Required-field completeness',
    description: 'All required KYC fields (legal name, DOB, government ID hash) populated on at least 99% of records.',
    sloType: 'completeness',
    metricName: 'required_field_completion_rate',
    thresholdOperator: 'gte',
    thresholdValue: 0.99,
    thresholdUnit: 'ratio',
    evaluationWindowHours: 24,
  },
  {
    productSlug: 'transaction-risk-signals',
    name: 'Risk score latency',
    description: 'p95 latency from transaction submission to risk score emission stays below 250ms.',
    sloType: 'latency',
    metricName: 'risk_score_p95_ms',
    thresholdOperator: 'lt',
    thresholdValue: 250,
    thresholdUnit: 'ms',
    evaluationWindowHours: 1,
  },
  {
    productSlug: 'transaction-risk-signals',
    name: 'Stream freshness',
    description: 'Risk signals on the streaming topic stay within 5 minutes of source transaction time.',
    sloType: 'freshness',
    metricName: 'risk_signal_lag_seconds',
    thresholdOperator: 'lt',
    thresholdValue: 300,
    thresholdUnit: 'seconds',
    evaluationWindowHours: 1,
  },
  {
    productSlug: 'credit-risk-decisions',
    name: 'Decision API latency',
    description: 'p99 latency on the credit decision endpoint stays below 2 seconds.',
    sloType: 'latency',
    metricName: 'decision_p99_ms',
    thresholdOperator: 'lt',
    thresholdValue: 2000,
    thresholdUnit: 'ms',
    evaluationWindowHours: 1,
  },
  {
    productSlug: 'credit-risk-decisions',
    name: 'Decision rationale coverage',
    description: 'At least 95% of decisions include a structured rationale payload for downstream review.',
    sloType: 'completeness',
    metricName: 'rationale_coverage_rate',
    thresholdOperator: 'gte',
    thresholdValue: 0.95,
    thresholdUnit: 'ratio',
    evaluationWindowHours: 24,
  },
  {
    productSlug: 'account-lifecycle-events',
    name: 'Lifecycle event lag',
    description: 'Account lifecycle events appear on the topic within 60 seconds of the source mutation.',
    sloType: 'freshness',
    metricName: 'lifecycle_event_lag_seconds',
    thresholdOperator: 'lt',
    thresholdValue: 60,
    thresholdUnit: 'seconds',
    evaluationWindowHours: 1,
  },
  {
    productSlug: 'account-lifecycle-events',
    name: 'State-transition completeness',
    description: 'At least 99% of expected state transitions (open, suspended, closed) are captured on the topic.',
    sloType: 'completeness',
    metricName: 'state_transition_capture_rate',
    thresholdOperator: 'gte',
    thresholdValue: 0.99,
    thresholdUnit: 'ratio',
    evaluationWindowHours: 24,
  },
];
